[build]
  command = "cd assessment-app && npm install && npm run build && cd .. && cp -r assessment-app/dist assessment"
  publish = "."

[[redirects]]
  from = "/assessment/*"
  to = "/assessment/index.html"
  status = 200

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  NETLIFY_SKIP_NEXTJS_PLUGIN = "true"
  VITE_GOOGLE_SHEET_URL = "https://script.google.com/macros/s/AKfycbywU1hsD3wcQUafXFSgZJzUB2d2uNxdWkljcUxAkw3IKBd4NfykC8fauRQzB8mrRY7Vfg/exec"
